import '../styles/globals.css'
import Head from 'next/head'
import AvaibleInvestments from './components/AvaibleInvestments'
import Benefits from './components/Benefits'
import FAQ from './components/faq'
import Hero from './components/Hero'
import HowItWorks from './components/howItWorks'
import ReachGoals from './components/ReachGoals'
import Team from './components/Team'
import WhyUs from './components/WhyUs'
//yepegow204@cmeinbox.com

export default function Home() {
  return (
    <div>
      <Head>
        <title>Reity Clone Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
     
          <Hero/>
          <Benefits/>
          <AvaibleInvestments/>
          <WhyUs/>
          <HowItWorks/>
          <ReachGoals/>
          <Team/>
          <FAQ/>
      
      </main>
    </div>
  )
}
